name: 'Get and Cache Dependencies'
description: 'Get the dependencies(via npm) and cache them'


inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
  cached_directory:
    description: 'Directory to be cached like "node_modules"'
    required: true


outputs:
  cache-on:
    description: 'Caching on?'
    value: ${{ steps.cache-status.outputs.cache-on }}
  cache-hit:
    description: 'Caching hit?'
    value: ${{ steps.cache-status.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Print inputs
      run: |
        echo "caching : ${{inputs.caching}}"
        echo "cached_directory : ${{inputs.cached_directory}}"
      shell: bash
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cached_directory }}
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Caching information
      id: cache-status
      run: |
        echo "cache-on='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
        echo "cache-hit='${{ steps.cache.outputs.cache-hit }}'" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
      shell: bash
